---
- name: Add apt_key
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-4.2.asc
    state: present
  tags: install

- name: Add mongoDB repo
  apt_repository:
    repo: deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse
    filename: /etc/apt/sources.list.d/mongodb-org-4.2.list
    state: present
  tags: install

- name: Install modngoDB
  apt:
    name: mongodb-org
    state: present
    update_cache: yes
  tags: install

- name: Enable mongodb service
  systemd:
    name: mongod
    enabled: yes
    state: started
  tags: install
